config/routes.rb
Rails.application.routes.draw do
  resources :urls

  root 'urls#new'
  get '/:request' => 'urls#redirect'
  get '/:request/stat' => 'urls#stat'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
	is_impressionable
	validates :original_url, :url => true
	validates :original_url, :uniqueness => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
	def new

	end

	def create
		if @url = Url.find_by(url_params)
			@url = Url.find_by(url_params)
			redirect_to @url
		else
			@url = Url.new(url_params)
			if @url.save
				@url.output_url = shorten(@url.id, '')
				@url.save
				redirect_to @url
			else
				redirect_to root_path
			end	
		end
	end

	def show
		@url = Url.find(params[:id])
	end

	def redirect
		if @url = Url.find_by(output_url: params[:request])
			@url = Url.find_by(output_url: params[:request])
			impressionist(@url) #count redirection here
			redirect_to @url.original_url
		else
			redirect_to root_path, alert: "Sorry, your request is not valid"
		end	
	end

	def stat
		if @url = Url.find_by(output_url: params[:request])
			@url = Url.find_by(output_url: params[:request])
		else
			redirect_to root_path, alert: "Sorry, your request is not valid" 
		end
	end

private

	def url_params
		params.require(:url).permit(:original_url)

	end

	def shorten(i, a)	#needs clearer rewriting
		s = 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  		a = a + s[i%62];
  		if i < 62 then
  	    	return a.reverse
  		else
  	    	shorten(i/62, a)
  		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShortenMe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/new.html.erb
<%= stylesheet_link_tag "style" %>

<% :alert %> 

<div class="container" align="center">

	<h1 class="display-4">URL Shortening Service</h1>
	<%= form_for :url, url: urls_path do |f| %>

		<div class="row">
		  <div class="col-lg-12">
		    <div class="input-group">
		      <%= f.url_field :original_url, class: "form-control", placeholder: "Paste your URL here.." %>
		      <span class="input-group-btn">
		        <button type= "submit" class="btn btn-secondary" type="button">Shorten</button>
		      </span>
		    </div>
		  </div>
		</div>
 
	<% end %>

</div>

app/views/urls/show.html.erb
<%= stylesheet_link_tag "style_show" %>

<h1>Information</h1>
<p>Your original URL: <%= @url.original_url %></p>
<p>Shortened URL: localhost:3000/<%= @url.output_url %> </p>

app/views/urls/stat.html.erb
<%= stylesheet_link_tag "style_show" %>

<h1> Statistics for localhost:3000/<%= @url.output_url %>:</h1>
<p> Original URL: <%= @url.original_url %> </p>
<p> Total hit: <%= @url.impressionist_count %></p>